-- MySQL Script generated by MySQL Workbench
-- Sun Apr 22 06:32:36 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema KoF-DiscordBotDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema KoF-DiscordBotDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `KoF-DiscordBotDB` DEFAULT CHARACTER SET utf8 ;
USE `KoF-DiscordBotDB` ;

-- -----------------------------------------------------
-- Table `KoF-DiscordBotDB`.`player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KoF-DiscordBotDB`.`player` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(100) NULL,
  `victories` INT NULL,
  `defeats` INT NULL,
  `country` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KoF-DiscordBotDB`.`game_version`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KoF-DiscordBotDB`.`game_version` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `year` INT NULL,
  `version` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KoF-DiscordBotDB`.`characters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KoF-DiscordBotDB`.`characters` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `game` INT NOT NULL,
  `picked` INT NULL,
  `round_win` INT NULL,
  `round_loss` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_characters_game_version1_idx` (`game` ASC),
  CONSTRAINT `fk_characters_game_version1`
    FOREIGN KEY (`game`)
    REFERENCES `KoF-DiscordBotDB`.`game_version` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KoF-DiscordBotDB`.`team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KoF-DiscordBotDB`.`team` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `characterOne` INT NOT NULL,
  `characterTwo` INT NOT NULL,
  `characterThree` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_team_characters_idx` (`characterOne` ASC),
  INDEX `fk_team_characters1_idx` (`characterTwo` ASC),
  INDEX `fk_team_characters2_idx` (`characterThree` ASC),
  CONSTRAINT `fk_team_characters`
    FOREIGN KEY (`characterOne`)
    REFERENCES `KoF-DiscordBotDB`.`characters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_team_characters1`
    FOREIGN KEY (`characterTwo`)
    REFERENCES `KoF-DiscordBotDB`.`characters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_team_characters2`
    FOREIGN KEY (`characterThree`)
    REFERENCES `KoF-DiscordBotDB`.`characters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KoF-DiscordBotDB`.`matches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KoF-DiscordBotDB`.`matches` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `playerOne` INT NOT NULL,
  `playerTwo` INT NOT NULL,
  `teamPlayerOne` INT NOT NULL,
  `teamPlayerTwo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_matches_player1_idx` (`playerOne` ASC),
  INDEX `fk_matches_player2_idx` (`playerTwo` ASC),
  INDEX `fk_matches_team1_idx` (`teamPlayerOne` ASC),
  INDEX `fk_matches_team2_idx` (`teamPlayerTwo` ASC),
  CONSTRAINT `fk_matches_player1`
    FOREIGN KEY (`playerOne`)
    REFERENCES `KoF-DiscordBotDB`.`player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matches_player2`
    FOREIGN KEY (`playerTwo`)
    REFERENCES `KoF-DiscordBotDB`.`player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matches_team1`
    FOREIGN KEY (`teamPlayerOne`)
    REFERENCES `KoF-DiscordBotDB`.`team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matches_team2`
    FOREIGN KEY (`teamPlayerTwo`)
    REFERENCES `KoF-DiscordBotDB`.`team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KoF-DiscordBotDB`.`round_score`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KoF-DiscordBotDB`.`round_score` (
  `idTeam` INT NOT NULL,
  `idChar` INT NOT NULL,
  `roundWin` INT NULL,
  `roundDeafeated` INT NULL,
  PRIMARY KEY (`idTeam`, `idChar`),
  INDEX `fk_team_has_characters_characters1_idx` (`idChar` ASC),
  INDEX `fk_team_has_characters_team1_idx` (`idTeam` ASC),
  CONSTRAINT `fk_team_has_characters_team1`
    FOREIGN KEY (`idTeam`)
    REFERENCES `KoF-DiscordBotDB`.`team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_team_has_characters_characters1`
    FOREIGN KEY (`idChar`)
    REFERENCES `KoF-DiscordBotDB`.`characters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KoF-DiscordBotDB`.`championship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KoF-DiscordBotDB`.`championship` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `dateStart` VARCHAR(45) NULL,
  `dateEnd` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KoF-DiscordBotDB`.`podium`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KoF-DiscordBotDB`.`podium` (
  `championship_id` INT NOT NULL,
  `player_id` INT NOT NULL,
  `playerPosition` INT NULL,
  PRIMARY KEY (`championship_id`, `player_id`),
  INDEX `fk_championship_has_player_player1_idx` (`player_id` ASC),
  INDEX `fk_championship_has_player_championship1_idx` (`championship_id` ASC),
  CONSTRAINT `fk_championship_has_player_championship1`
    FOREIGN KEY (`championship_id`)
    REFERENCES `KoF-DiscordBotDB`.`championship` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_championship_has_player_player1`
    FOREIGN KEY (`player_id`)
    REFERENCES `KoF-DiscordBotDB`.`player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
